# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Info-App' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Info-App
  pod 'SDWebImage', :modular_headers => true
  pod 'SnapKit', '~> 4.0.0'
  pod 'HexColors'
  pod 'Toast-Swift'
  pod 'ReachabilitySwift'

  target 'Info-AppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
