# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Info-App' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Info-App
  pod 'ObjectMapper', '3.3.0'

  target 'Info-AppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
